name: ParaTranz To GT Lang

on:
  issues:
    types: [ opened ]

env:
  PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
  PARATRANZ_PROJECT_ID: ${{ secrets.PARATRANZ_PROJECT_ID }}
  TARGET_LANG: pt_BR

jobs:
  check-and-parse-issue:
    if: contains(github.event.issue.labels.*.name, 'Automação:paratranz→gt-lang')
    name: Check And Parse Issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GTNH-Portuguese-Translation/GTNH-translation-compare-portuguese
        uses: actions/checkout@v3
        with:
          repository: GTNH-Portuguese-Translation/GTNH-translation-compare-portuguese
          ref: main
      - name: Ensure Dependencies
        uses: ./.github/actions/ensure-dependencies
      - name: Run Script
        id: check-and-parse-issue
        env:
          GITHUB_ISSUE: ${{ toJSON(github.event.issue) }}
          VALID_LABEL: Automação:paratranz→gt-lang
          VALID_USER: ${{ github.repository_owner }}
        run: |
          poetry run python main.py parse-issue paratranz-to-gt-lang
    outputs:
      passed: ${{ steps.check-and-parse-issue.outputs.passed }}
      branch: ${{ steps.check-and-parse-issue.outputs.branch }}

  close-issue:
    name: Close Issue
    needs: check-and-parse-issue
    if: ${{ needs.check-and-parse-issue.outputs.passed != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        run: gh issue close "${ISSUE_URL}" --comment "Este template foi fechado automaticamente pois deve ser usado somente para uso interno."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}

  paratranz-to-gt-lang:
    name: ParaTranz To GT Lang
    needs: check-and-parse-issue
    if: ${{ needs.check-and-parse-issue.outputs.passed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GTNH-Portuguese-Translation/GTNH-translation-compare-portuguese
        uses: actions/checkout@v3
        with:
          repository: GTNH-Portuguese-Translation/GTNH-translation-compare-portuguese
          ref: main
      - name: Ensure Dependencies
        uses: ./.github/actions/ensure-dependencies
      - name: Checkout Work Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.check-and-parse-issue.outputs.branch }}
          path: '.repo'
      - name: Run Script
        run: >-
          poetry run python main.py action paratranz-to-gt-lang
          --repo-path='.repo'
          --issue='${{ github.event.issue.number }}'
          --commit-message='[Automatizado] Atualizar GregTech.lang.'
      - name: Create PR
        uses: peter-evans/create-pull-request@v4.0.0
        with:
          title: '[Automatizado] Atualizar GregTech.lang.'
          labels: |
            Auutomação:paratranz→gt-lang
          body: |
            Ativado por: #${{ github.event.issue.number }}
          base: ${{ needs.check-and-parse-issue.outputs.branch }}
          branch: automation/compare/${{ github.event.issue.number }}
          path: '.repo'
          delete-branch: true
